spring:
  datasource:
    url: jdbc:mysql://liumengxiao.cn:3306/proj?serverTimezone=GMT%2b8
    username: proj
    password: unamedgroup
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect.
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
server:
  port: 8080
  address: 0.0.0.0
